// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuQGK8UoWMXjL6vD7YAh0zhMCnDdQ0bOM',
    appId: '1:683682163179:web:6a2e2384bb26973c4351ae',
    messagingSenderId: '683682163179',
    projectId: 'indianconstitution-a306a',
    authDomain: 'indianconstitution-a306a.firebaseapp.com',
    storageBucket: 'indianconstitution-a306a.firebasestorage.app',
    measurementId: 'G-NR9ESJND5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7LMZbOBs18P1DENSWeN6INujAlOvyZ9w',
    appId: '1:683682163179:android:0ae54442db0ed46c4351ae',
    messagingSenderId: '683682163179',
    projectId: 'indianconstitution-a306a',
    storageBucket: 'indianconstitution-a306a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGE2hU_sIAuo6Z9v6mMQ3FueE1HnNSPw8',
    appId: '1:683682163179:ios:f1c492e2e48be7a94351ae',
    messagingSenderId: '683682163179',
    projectId: 'indianconstitution-a306a',
    storageBucket: 'indianconstitution-a306a.firebasestorage.app',
    iosBundleId: 'com.example.coi',
  );
}
